# Campaign
campaign_id: 1

# Forward model parameters

# Learning model parameters
data_file: ignition_time_gri_mech.dat # Used to generate the training data

# data_file: ytrain.npy
model_noise_cov: 1.0e-1
objective_scaling: 1.0e-12

# Leaning model 
compute_map: True
compute_mle: False

# Identifiability
compute_identifiability: False
global_num_outer_samples: 10000
global_num_inner_samples: 5
restart_identifiability: False

