# Campaign
campaign_id: 9

# Forward model parameters

# Learning model parameters
data_file: ignition_time_gri_mech.dat # Used to generate the training data

# data_file: ytrain.npy
model_noise_cov: 1.0e+0
objective_scaling: 1.0e-12

# Leaning model 
compute_map: False
compute_mle: True

# Identifiability
compute_identifiability: True
global_num_outer_samples: 10
global_num_inner_samples: 5
restart_identifiability: False

