campaign_id: 1

total_samples: 100
num_samples: 100

model_noise_cov: 1.0e-1
objective_scaling: 1.0e-10

# 
compute_map: False 
compute_mle: False

#
compute_identifiability: True
global_num_outer_samples: 10000
global_num_inner_samples: 5000
restart_identifiability: False



